# Generated by Django 3.1.1 on 2021-03-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=100)),
                ('catImg', models.ImageField(default='picture_1457X446.jpg', upload_to='blog/categoryImage')),
                ('des', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=150, null=True)),
                ('password', models.CharField(max_length=150)),
                ('bio', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(null=True)),
                ('content', models.TextField(max_length=3000)),
                ('thumb', models.ImageField(default='thumb.png', upload_to='blog/postthumb')),
                ('banner', models.ImageField(default='banner.png', upload_to='blog/postbanner')),
                ('view', models.IntegerField(default=0)),
                ('tag', models.TextField(blank=True, max_length=200, null=True)),
                ('pic1', models.ImageField(blank=True, default='', null=True, upload_to='blog/postpic')),
                ('pic2', models.ImageField(blank=True, default='', null=True, upload_to='blog/postpic')),
                ('pic3', models.ImageField(blank=True, default='', null=True, upload_to='blog/postpic')),
                ('pic4', models.ImageField(blank=True, default='', null=True, upload_to='blog/postpic')),
                ('pic5', models.ImageField(blank=True, default='', null=True, upload_to='blog/postpic')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.bloguser')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(default='https://wa.me/', max_length=100, null=True)),
                ('whatsappIcon', models.CharField(blank=True, default='fab fa-whatsapp', max_length=100)),
                ('youtube', models.CharField(default='https://www.youtube.com/', max_length=100, null=True)),
                ('youtubeIcon', models.CharField(blank=True, default='fab fa-youtube', max_length=100)),
                ('linkedin', models.CharField(default='https://www.linkedin.com/in/', max_length=100, null=True)),
                ('linkedinIcon', models.CharField(blank=True, default='fab fa-linkedin', max_length=100)),
                ('github', models.CharField(default='https://www.github.com/', max_length=100, null=True)),
                ('githubIcon', models.CharField(blank=True, default='fab fa-github', max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.bloguser')),
            ],
        ),
        migrations.CreateModel(
            name='PostPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(default='picture_1457X446.jpg', upload_to='blog/postpic')),
                ('pic2', models.ImageField(default='picture_1457X446.jpg', upload_to='blog/postpic')),
                ('pic3', models.ImageField(default='picture_1457X446.jpg', upload_to='blog/postpic')),
                ('pic4', models.ImageField(default='picture_1457X446.jpg', upload_to='blog/postpic')),
                ('pic5', models.ImageField(default='picture_1457X446.jpg', upload_to='blog/postpic')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.post')),
            ],
        ),
    ]
