# Generated by Django 3.1.1 on 2021-03-20 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.ImageField(blank=True, default='profile.png', null=True, upload_to='blog/userPic')),
                ('banner', models.ImageField(blank=True, default='banner.jpg', null=True, upload_to='blog/userBanner')),
                ('bio', models.TextField(max_length=500, null=True)),
                ('phone', models.IntegerField(default=0, null=True)),
                ('verifyed', models.BooleanField(default=False, null=True)),
                ('link1', models.CharField(default='https://wa.me/', max_length=100, null=True)),
                ('link1Icon', models.CharField(blank=True, default='fab fa-whatsapp', max_length=100)),
                ('link2', models.CharField(default='https://www.youtube.com/', max_length=100, null=True)),
                ('link2Icon', models.CharField(blank=True, default='fab fa-youtube', max_length=100)),
                ('link3', models.CharField(default='https://www.linkedin.com/in/', max_length=100, null=True)),
                ('link3Icon', models.CharField(blank=True, default='fab fa-linkedin', max_length=100)),
                ('link4', models.CharField(default='https://www.github.com/', max_length=100, null=True)),
                ('link4Icon', models.CharField(blank=True, default='fab fa-github', max_length=100)),
                ('userName', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='postpic',
            name='post',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='cat',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BlogUser',
        ),
        migrations.DeleteModel(
            name='PostPic',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
