# Generated by Django 3.1.1 on 2021-03-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210320_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogusermodel',
            name='phone',
            field=models.CharField(default='', max_length=12, null=True),
        ),
    ]
