# Generated by Django 3.1.1 on 2021-03-20 14:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20210320_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogUserModel',
            new_name='UserProfile',
        ),
    ]
