# Generated by Django 3.1.1 on 2021-02-23 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('biobanner', models.CharField(blank=True, max_length=200, null=True)),
                ('bioindex', models.CharField(blank=True, max_length=500, null=True)),
                ('bioabout', models.CharField(blank=True, max_length=700, null=True)),
                ('email1', models.EmailField(max_length=100)),
                ('email2', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=200)),
                ('phone1', models.IntegerField(max_length=10)),
                ('phone2', models.IntegerField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('instituteName', models.CharField(blank=True, max_length=100, null=True)),
                ('board', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('logoPic', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.bio')),
            ],
        ),
        migrations.CreateModel(
            name='AreaIntrest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.bio')),
            ],
        ),
    ]
