# Generated by Django 3.1.1 on 2021-02-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210223_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='subjectdes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
