# Generated by Django 3.1.1 on 2021-02-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210223_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='logoPic',
        ),
        migrations.RemoveField(
            model_name='skillset',
            name='logoPic',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='logoPic',
        ),
        migrations.AddField(
            model_name='bio',
            name='profilePic',
            field=models.ImageField(default='', upload_to='portfolio/profilePic'),
        ),
        migrations.AddField(
            model_name='education',
            name='iconsPic',
            field=models.ImageField(default='idef.jpg', upload_to='portfolio/icons'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_pic',
            field=models.ImageField(default='pdef.jpg', upload_to='portfolio/projects'),
        ),
        migrations.AddField(
            model_name='skillset',
            name='logo_FontAws_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='logo_FontAws_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='Images',
            field=models.ImageField(default='cdef.jpg', upload_to='portfolio/certificates'),
        ),
    ]
