# Generated by Django 3.1.1 on 2021-02-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210224_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='bannerPic',
            field=models.ImageField(default='', upload_to='portfolio/bannerPic'),
        ),
    ]
