# Generated by Django 3.1.1 on 2021-02-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_bio_bannerpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='tagLine',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='email1',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='phone1',
            field=models.IntegerField(unique=True),
        ),
    ]
