# Generated by Django 3.1.1 on 2021-02-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20210224_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillset',
            old_name='logo_FontAws_class',
            new_name='logo_class',
        ),
    ]
