# Generated by Django 3.1.1 on 2021-02-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210224_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='feture',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
