# Generated by Django 3.1.1 on 2021-02-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_projects_feture'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='feture_pic',
            field=models.ImageField(default='fdef.jpg', upload_to='portfolio/Feature'),
        ),
    ]
