# Generated by Django 3.1.1 on 2021-02-24 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_projects_feture_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='des',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='logo_FontAws_class',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='siteURL',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='sitename',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='github',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='githubIcon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='linkedin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='linkedinIcon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='whatsapp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='whatsappIcon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='youtube',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='youtubeIcon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.bio'),
        ),
    ]
