# Generated by Django 3.1.1 on 2021-02-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20210224_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='areaIntrest',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='github',
            field=models.CharField(default='https://www.github.com/', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='githubIcon',
            field=models.CharField(blank=True, default='fab fa-github', max_length=100),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='linkedin',
            field=models.CharField(default='https://www.linkedin.com/in/', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='linkedinIcon',
            field=models.CharField(blank=True, default='fab fa-linkedin', max_length=100),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='whatsapp',
            field=models.CharField(default='https://wa.me/', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='whatsappIcon',
            field=models.CharField(blank=True, default='fab fa-whatsapp', max_length=100),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='youtube',
            field=models.CharField(default='https://www.youtube.com/', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='youtubeIcon',
            field=models.CharField(blank=True, default='fab fa-youtube', max_length=100),
        ),
        migrations.DeleteModel(
            name='AreaIntrest',
        ),
    ]
