# Generated by Django 3.1.1 on 2021-02-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20210224_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='tittle',
            new_name='title',
        ),
    ]
