# Generated by Django 3.1.1 on 2021-02-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20210224_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbies',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.bio'),
        ),
    ]
