# Generated by Django 3.1.1 on 2021-02-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20210224_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='des',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='institute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='procat',
            name='des',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='procat',
            name='feture_pic',
            field=models.ImageField(blank=True, default='fdef.jpg', null=True, upload_to='portfolio/Feature'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='areaIntrest',
            field=models.CharField(blank=True, default='Electronic', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.bio'),
        ),
        migrations.AlterField(
            model_name='education',
            name='board',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='iconsPic',
            field=models.ImageField(blank=True, default='idef.jpg', null=True, upload_to='portfolio/icons'),
        ),
        migrations.AlterField(
            model_name='education',
            name='instituteName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.bio'),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.bio'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.procat'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='des',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='feture_pic',
            field=models.ImageField(blank=True, default='fdef.jpg', null=True, upload_to='portfolio/Feature'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='proGithub',
            field=models.CharField(blank=True, default='https://github.com/Error57nk', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='proStatus',
            field=models.CharField(blank=True, default='Completed', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_pic',
            field=models.ImageField(blank=True, default='pdef.jpg', null=True, upload_to='portfolio/projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='techused',
            field=models.CharField(default='python', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='logo_class',
            field=models.CharField(blank=True, default='fas fa-shield-alt', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='tittle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.bio'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.bio'),
        ),
    ]
