# Generated by Django 3.1.1 on 2021-02-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20210225_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='phone1',
            field=models.CharField(default='91', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='phone2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
