# Generated by Django 3.1.1 on 2021-02-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20210225_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbies',
            name='des',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
