# Generated by Django 3.1.1 on 2021-02-26 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_auto_20210225_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='phone1',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='phone2',
            field=models.CharField(blank=True, default='empty', max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='English', max_length=50)),
                ('des', models.CharField(default='Read, Write, Speak', max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.bio')),
            ],
        ),
    ]
