# Generated by Django 3.1.1 on 2021-03-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_auto_20210226_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='bannerPic',
            field=models.ImageField(default='picture_1457X446.jpg', upload_to='portfolio/bannerPic'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='profilePic',
            field=models.ImageField(default='picture_220X220.jpg', upload_to='portfolio/profilePic'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='Images',
            field=models.ImageField(default='picture_400X300.jpg', upload_to='portfolio/certificates'),
        ),
        migrations.AlterField(
            model_name='education',
            name='iconsPic',
            field=models.ImageField(blank=True, default='picture_64X64.jpg', null=True, upload_to='portfolio/icons'),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='images',
            field=models.ImageField(default='picture_350X200.jpg', upload_to='portfolio/hobbies'),
        ),
        migrations.AlterField(
            model_name='procat',
            name='feture_pic',
            field=models.ImageField(blank=True, default='picture_64X64.jpg', null=True, upload_to='portfolio/Feature'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='feture_pic',
            field=models.ImageField(blank=True, default='picture_300X300.jpg', null=True, upload_to='portfolio/Feature'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='proDownload',
            field=models.CharField(blank=True, default='Only For Android', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_pic',
            field=models.ImageField(blank=True, default='picture_500X300.jpg', null=True, upload_to='portfolio/projects'),
        ),
    ]
